### ISSUE TITLE
Remove component nesting

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#108]
We have over 1000 nested components in the GS / GST designs. In the latest fontbakery release, this design approach is flagged as a fail in the new `com.google.fonts/check/glyf_nested_components` universal profile check.

Our CI: https://github.com/googlefonts/googlesans/runs/1453872062?check_suite_focus=true

fontbakery rationale: https://github.com/googlefonts/fontbakery/issues/2961

We'll need to address this new fail. Niko proposed unnesting components at compile time with the approach in https://github.com/googlefonts/fontbakery/issues/2961#issuecomment-733745539.

Let's investigate further and determine how we should address this.

cc @Colophon-Foundry @madig @belluzj 

Requires #246 

---

### TODO

- [x] confirm that there is no regression with required ufo2ft dependency bump (https://github.com/googlefonts/googlesans/issues/246)
- [x] update ufo2ft
- [x] remove nested components
- [x] eyeballs on modified glyphs (glyph lists attached in text files below)

[Regular.txt](https://github.com/googlefonts/googlesans/files/6083938/Regular.txt)
[Italic.txt](https://github.com/googlefonts/googlesans/files/6083941/Italic.txt)

**Comment by chrissimpkins** [comment]
@Colophon-Foundry is the component nesting something new that came about in v3.000 or has this been in place across production builds since the Google Sans v2.x releases?

**Comment by chrissimpkins** [comment]
From @madig in https://github.com/googlefonts/googlesans/issues/106#issuecomment-733831309

Default statics: + ~3 KB
Variable full: + ~ 6-7 KB
Variable subsets: + ~4-5 KB

Without doing any deeper research into it or even testing if the fonts work as before.

**Comment by chrissimpkins** [comment]
@nyshadhr9 @davelab6 Thoughts about this file size increase to satisfy the fontbakery nested component check FAILs?  These were introduced into FB based on https://github.com/googlefonts/fontbakery/issues/2961

**Comment by chrissimpkins** [comment]
Supported in new fontmake `--flatten-components` option as of v2.3.0

https://github.com/googlefonts/fontmake/releases/tag/v2.3.0

**Comment by madig** [comment]
Also supported by a ufo2ft filter before.

**Comment by chrissimpkins** [comment]
I used this in another project today.   Works!

**Comment by chrissimpkins** [comment]
@madig this will be closed in the new build workflow?

**Comment by madig** [comment]
No, it would be a separate PR so we keep it focused.

**Comment by davelab6** [comment]
We should do it, the file size is worth it

**Comment by chrissimpkins** [comment]
Added to v3.004

**Comment by chrissimpkins** [comment]
Related #116

**Comment by chrissimpkins** [comment]
> We should do it, the file size is worth it

@davelab6 Initial assessment of the file size impact of component "de-nesting"  https://github.com/googlefonts/googlesans/pull/124#issuecomment-761581545

**Comment by chrissimpkins** [comment]
Nested components will be included in David Berlow's grade axis expansion sources.  We'll need to use the compiler to address this issue.
