### ISSUE TITLE
Add harfbuzz shaping regression tests for Latin, Greek, Cyrillic, Hebrew production scripts

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#161]
## High priority

- [x] calt (https://github.com/googlefonts/googlesans/pull/165)
- [x] case (https://github.com/googlefonts/googlesans/pull/166)
- [x] ccmp (Latin, Hebrew https://github.com/googlefonts/googlesans/pull/179)
- [x] dnom (https://github.com/googlefonts/googlesans/pull/168)
- [x] frac (https://github.com/googlefonts/googlesans/pull/147)
- [x] jalt (https://github.com/googlefonts/googlesans/pull/169)
- [x] kern (#180)
- [x] liga (https://github.com/googlefonts/googlesans/pull/170)
- [x] locl (Cyrillic https://github.com/googlefonts/googlesans/pull/164, Latin #189 )
- [x] numr (https://github.com/googlefonts/googlesans/pull/173)
- [x] ordn (https://github.com/googlefonts/googlesans/pull/172)
- [x] pnum (https://github.com/googlefonts/googlesans/pull/171)
- [x] sinf (https://github.com/googlefonts/googlesans/pull/173)
- [x] subs (https://github.com/googlefonts/googlesans/pull/173)
- [x] sups (https://github.com/googlefonts/googlesans/pull/173)
- [x] tnum (https://github.com/googlefonts/googlesans/pull/171)

## Medium priority

- [x] c2sc (#198)
- [x] dlig (https://github.com/googlefonts/googlesans/pull/167)
- [x] smcp (#190)
- [ ] liga + smcp strings (see https://github.com/googlefonts/googlesans/issues/69#issuecomment-784711656)

## Low priority

- [ ] lnum
- [x] ss01 (#205)
- [x] ss02 (#205)
- [x] ss03 (https://github.com/googlefonts/googlesans/pull/174)
- [x] ss04 (#190)
- [x] ss05 (https://github.com/googlefonts/googlesans/pull/183)
- [x] ss06 (https://github.com/googlefonts/googlesans/pull/184)
- [ ] ss07

## Will not test

- [x] aalt (to be removed in v4)
- [x] ss08 (to be removed in v4)

---

### TODO:

- [x] discuss Hebrew regression testing with Daniel Grumer
- [x] discuss Greek regression testing with Irene Vlachou
- [x] discuss Cyrillic regression testing with Alexei Vanyashin

**Comment by chrissimpkins** [comment]
Related: https://github.com/googlefonts/googlesans/issues/157#issuecomment-774117550

**Comment by chrissimpkins** [comment]
@madig, possible to pull out any regression tests that you have stowed away in PR's with other work so that we can merge them?  Full fea coverage list is indicated in the OP here.  We're getting close.

**Comment by madig** [comment]
I have stuff in my rvrn branch, soon!

**Comment by chrissimpkins** [comment]
> I have stuff in my rvrn branch, soon!

Will take a look and return to whatever we don't have here later today.

**Comment by madig** [comment]
Did you put up your toml->json script somewhere?

**Comment by madig** [comment]
Ok, let's see what you have :D @chrissimpkins

**Comment by madig** [comment]
@irenevl the `ccmp` feature contains some Greek mark juggling. Can you give examples for where these lookups are needed?

**Comment by madig** [comment]
Testing the stuff in ccmp_Other_1 seems tricky because HarfBuzz will replace combinations it finds as precomposed glyphs with those immediately and I'm not sure testing `i̊i̮̊j̇` is useful. The lower half of that lookup has to do with Greek, where I don't know how it's used. ccmp_Other_2 seems to continue that and probably case all of the marks. ccmp_latn_1 ligates things, which works, except for the .cap stuff. Those can't occur in text because they lack a Unicode value, but doing e.g. "A\u0306\u0301" will immediately replace it with the precomposed glyph...

**Comment by moyogo** [comment]
@madig `ccmp_Other1`, `ccmp_Other_2`, `ccmp_latn_1` were automatically generated by Glyphs.app at some point, these are the names it uses when it generates the ccmp feature.

I don't think we need the Greek part of `ccmp_Other_1` nor `ccmp_Other_2`, these replace `[tonos psili koronis dasia dasiavaria psilioxia dasiaoxia psiliperispomeni dasiaperispomeni dialytikavaria dialytikaperispomeni varia oxia perispomeni psilivaria dialytikaoxia]` by their case variants when they are in a sequence of two or more, or when they are after an uppercase.
But these are characters that are not combining marks. They don't attach to base letters, don't stack horizontally or vertically, nor should be non-spacing. So there's no need for them to change in those sequences.
The sequences that would occur would use `[acutecomb gravecomb perispomenicomb commaabovecomb commareversedabovecomb]` for example ὀ͂. All would have Greek specific variants, except for perispomenicomb which is only used in Greek. They and their ligatures would be the non-spacing combining equivalents of the spacing ones. This is probably out of scope since they occur in ancient texts.

The Latin part of `ccmp_Other_1` is for the softdotted property of i and j. It replace i or j by idotless or jdotless when they have a combining mark above in place of the tittle.
This is needed as some languages or transcriptions use these base letters with combining marks, and no precomposed glyph is available.
This should be extended with any character that has the [Soft_Dotted](http://unicode.org/reports/tr44/#Soft_Dotted) Unicode character property. At the moment that would just be /i/i-cy/idotbelow/iogonek/j/je-cy
 (i j į і ј ị) but there are more in the Latin expansion, where the rules are updated.

The lookup `ccmp_latn1` make ligatures for stacked marks and is useful for sequences that don't have precomposed glyphs. These specific ones are pretty rare, for example in Ĕ́ ĕ́, and mostly used in phonetic transcriptions except for the Vietnamese ones which have precomposed glyphs. For other sequences used in orthographies, mark-to-mark stacking is used in the Latin expansion when precomposed form don't exist.

**Comment by madig** [comment]
Thanks, then we'll only test soft-dots and stacking. Would _someone_ need to add a new iogonekdotless variant?

**Comment by moyogo** [comment]
> Thanks, then we'll only test soft-dots and stacking. Would someone need to add a new iogonekdotless variant?

That's in the Latin Expansion.

**Comment by chrissimpkins** [comment]
@madig OK if I add the toml -> JSON scripting to your `update_shaping_test_data.py` script rather than add in a separate script?  I think that we can use the same script to read TOML and dump final JSON files with full HB shaping output data.

**Comment by madig** [comment]
Yes, that's ok. We can build from there.

**Comment by chrissimpkins** [comment]
> Yes, that's ok. We can build from there.

#203
