### ISSUE TITLE
[GS v4] name table diff

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#217]
Review diff of name tables between David Berlow's source files @ https://github.com/googlefonts/GoogleSans-fb/commit/a8d2737ba302a95dcb692c8b8b05bdf481631cb0 and our v3.003 production releases

### TODO:

- [x] reimplement named instances
- [x] revert family name change back to "Google Sans" from "GoogleSans" Roman sources
- [x] revert family name change back to "Google Sans" from "GoogleSansItalic" Italic sources
- [x] check VF font name tables
- [x] check static font name tables

**Comment by chrissimpkins** [comment]
Roman varfont

- named instances need to be reimplemented
- family name is incorrect, needs to be changed from "GoogleSans" back to "Google Sans"

<details>
<summary>diff</summary>

```diff
--- A/GoogleSans[opsz,wght].ttf	2020-09-16T16:50:43-04:00
+++ B/GoogleSansGrades-VF.ttf	2021-02-25T11:12:08.527802-05:00
@@ -12,61 +12,34 @@
       Colon time
     </namerecord>
     <namerecord nameID="259" platformID="1" platEncID="0" langID="0x0" unicode="True">
+      Alternate Arrows
+    </namerecord>
+    <namerecord nameID="260" platformID="1" platEncID="0" langID="0x0" unicode="True">
+      Accented Greek SC
+    </namerecord>
+    <namerecord nameID="261" platformID="1" platEncID="0" langID="0x0" unicode="True">
+      iota adscript
+    </namerecord>
+    <namerecord nameID="262" platformID="1" platEncID="0" langID="0x0" unicode="True">
+      Bulgarian Locale
+    </namerecord>
+    <namerecord nameID="263" platformID="1" platEncID="0" langID="0x0" unicode="True">
       Thin Numbers
     </namerecord>
-    <namerecord nameID="260" platformID="1" platEncID="0" langID="0x0" unicode="True">
-      Alternate Arrows
-    </namerecord>
-    <namerecord nameID="261" platformID="1" platEncID="0" langID="0x0" unicode="True">
-      Accented Greek SC
-    </namerecord>
-    <namerecord nameID="262" platformID="1" platEncID="0" langID="0x0" unicode="True">
-      iota adscript
-    </namerecord>
-    <namerecord nameID="263" platformID="1" platEncID="0" langID="0x0" unicode="True">
-      Bulgarian Locale
-    </namerecord>
     <namerecord nameID="264" platformID="1" platEncID="0" langID="0x0" unicode="True">
-      Optical size
+      Optical Size
     </namerecord>
     <namerecord nameID="265" platformID="1" platEncID="0" langID="0x0" unicode="True">
       Weight
     </namerecord>
     <namerecord nameID="266" platformID="1" platEncID="0" langID="0x0" unicode="True">
-      Regular
-    </namerecord>
-    <namerecord nameID="267" platformID="1" platEncID="0" langID="0x0" unicode="True">
-      Medium
-    </namerecord>
-    <namerecord nameID="268" platformID="1" platEncID="0" langID="0x0" unicode="True">
-      Bold
-    </namerecord>
-    <namerecord nameID="269" platformID="1" platEncID="0" langID="0x0" unicode="True">
-      Text Regular
-    </namerecord>
-    <namerecord nameID="270" platformID="1" platEncID="0" langID="0x0" unicode="True">
-      Text Medium
-    </namerecord>
-    <namerecord nameID="271" platformID="1" platEncID="0" langID="0x0" unicode="True">
-      Text Bold
-    </namerecord>
-    <namerecord nameID="272" platformID="1" platEncID="0" langID="0x0" unicode="True">
-      Optical Size
-    </namerecord>
-    <namerecord nameID="273" platformID="1" platEncID="0" langID="0x0" unicode="True">
-      Max
-    </namerecord>
-    <namerecord nameID="274" platformID="1" platEncID="0" langID="0x0" unicode="True">
-      Text
-    </namerecord>
-    <namerecord nameID="275" platformID="1" platEncID="0" langID="0x0" unicode="True">
-      Italic
+      GRAD
     </namerecord>
     <namerecord nameID="0" platformID="3" platEncID="1" langID="0x409">
       Copyright 2015 Google LLC. All Rights Reserved.
     </namerecord>
     <namerecord nameID="1" platformID="3" platEncID="1" langID="0x409">
-      Google Sans
+      GoogleSans
     </namerecord>
     <namerecord nameID="2" platformID="3" platEncID="1" langID="0x409">
       Regular
@@ -75,7 +48,7 @@
       3.003;GOOG;GoogleSans-Regular
     </namerecord>
     <namerecord nameID="4" platformID="3" platEncID="1" langID="0x409">
-      Google Sans Regular
+      GoogleSans Regular
     </namerecord>
     <namerecord nameID="5" platformID="3" platEncID="1" langID="0x409">
       Version 3.003
@@ -108,55 +81,28 @@
       Colon time
     </namerecord>
     <namerecord nameID="259" platformID="3" platEncID="1" langID="0x409">
+      Alternate Arrows
+    </namerecord>
+    <namerecord nameID="260" platformID="3" platEncID="1" langID="0x409">
+      Accented Greek SC
+    </namerecord>
+    <namerecord nameID="261" platformID="3" platEncID="1" langID="0x409">
+      iota adscript
+    </namerecord>
+    <namerecord nameID="262" platformID="3" platEncID="1" langID="0x409">
+      Bulgarian Locale
+    </namerecord>
+    <namerecord nameID="263" platformID="3" platEncID="1" langID="0x409">
       Thin Numbers
     </namerecord>
-    <namerecord nameID="260" platformID="3" platEncID="1" langID="0x409">
-      Alternate Arrows
-    </namerecord>
-    <namerecord nameID="261" platformID="3" platEncID="1" langID="0x409">
-      Accented Greek SC
-    </namerecord>
-    <namerecord nameID="262" platformID="3" platEncID="1" langID="0x409">
-      iota adscript
-    </namerecord>
-    <namerecord nameID="263" platformID="3" platEncID="1" langID="0x409">
-      Bulgarian Locale
-    </namerecord>
     <namerecord nameID="264" platformID="3" platEncID="1" langID="0x409">
-      Optical size
+      Optical Size
     </namerecord>
     <namerecord nameID="265" platformID="3" platEncID="1" langID="0x409">
       Weight
     </namerecord>
     <namerecord nameID="266" platformID="3" platEncID="1" langID="0x409">
-      Regular
-    </namerecord>
-    <namerecord nameID="267" platformID="3" platEncID="1" langID="0x409">
-      Medium
-    </namerecord>
-    <namerecord nameID="268" platformID="3" platEncID="1" langID="0x409">
-      Bold
-    </namerecord>
-    <namerecord nameID="269" platformID="3" platEncID="1" langID="0x409">
-      Text Regular
-    </namerecord>
-    <namerecord nameID="270" platformID="3" platEncID="1" langID="0x409">
-      Text Medium
-    </namerecord>
-    <namerecord nameID="271" platformID="3" platEncID="1" langID="0x409">
-      Text Bold
-    </namerecord>
-    <namerecord nameID="272" platformID="3" platEncID="1" langID="0x409">
-      Optical Size
-    </namerecord>
-    <namerecord nameID="273" platformID="3" platEncID="1" langID="0x409">
-      Max
-    </namerecord>
-    <namerecord nameID="274" platformID="3" platEncID="1" langID="0x409">
-      Text
-    </namerecord>
-    <namerecord nameID="275" platformID="3" platEncID="1" langID="0x409">
-      Italic
+      GRAD
     </namerecord>
   </name>
```

</details>

**Comment by chrissimpkins** [comment]
Italic varfont

- named instances need to be reimplemented
- revert family name back to "Google Sans" from "GoogleSansItalic"
- it looks like the Italic sources were based on v3.001, need to review v3.001 - v3.003 changes to see what may have been missed in the Italic set (https://github.com/googlefonts/GoogleSans-fb/issues/14)


<details>
<summary>diff </summary>

```diff
--- A/GoogleSans-Italic[opsz,wght].ttf	2020-09-16T16:50:43-04:00
+++ B/GoogleSansItalicGrades-VF.ttf	2021-02-25T11:12:48.431719-05:00
@@ -24,64 +24,31 @@
       Bulgarian Locale
     </namerecord>
     <namerecord nameID="263" platformID="1" platEncID="0" langID="0x0" unicode="True">
-      Optical size
+      Optical Size
     </namerecord>
     <namerecord nameID="264" platformID="1" platEncID="0" langID="0x0" unicode="True">
       Weight
     </namerecord>
     <namerecord nameID="265" platformID="1" platEncID="0" langID="0x0" unicode="True">
-      Italic
-    </namerecord>
-    <namerecord nameID="266" platformID="1" platEncID="0" langID="0x0" unicode="True">
-      Medium Italic
-    </namerecord>
-    <namerecord nameID="267" platformID="1" platEncID="0" langID="0x0" unicode="True">
-      Bold Italic
-    </namerecord>
-    <namerecord nameID="268" platformID="1" platEncID="0" langID="0x0" unicode="True">
-      Text Italic
-    </namerecord>
-    <namerecord nameID="269" platformID="1" platEncID="0" langID="0x0" unicode="True">
-      Text Medium Italic
-    </namerecord>
-    <namerecord nameID="270" platformID="1" platEncID="0" langID="0x0" unicode="True">
-      Text Bold Italic
-    </namerecord>
-    <namerecord nameID="271" platformID="1" platEncID="0" langID="0x0" unicode="True">
-      Optical Size
-    </namerecord>
-    <namerecord nameID="272" platformID="1" platEncID="0" langID="0x0" unicode="True">
-      Max
-    </namerecord>
-    <namerecord nameID="273" platformID="1" platEncID="0" langID="0x0" unicode="True">
-      Text
-    </namerecord>
-    <namerecord nameID="274" platformID="1" platEncID="0" langID="0x0" unicode="True">
-      Regular
-    </namerecord>
-    <namerecord nameID="275" platformID="1" platEncID="0" langID="0x0" unicode="True">
-      Medium
-    </namerecord>
-    <namerecord nameID="276" platformID="1" platEncID="0" langID="0x0" unicode="True">
-      Bold
+      GRAD
     </namerecord>
     <namerecord nameID="0" platformID="3" platEncID="1" langID="0x409">
       Copyright 2015 Google LLC. All Rights Reserved.
     </namerecord>
     <namerecord nameID="1" platformID="3" platEncID="1" langID="0x409">
-      Google Sans
+      GoogleSansItalic
     </namerecord>
     <namerecord nameID="2" platformID="3" platEncID="1" langID="0x409">
       Italic
     </namerecord>
     <namerecord nameID="3" platformID="3" platEncID="1" langID="0x409">
-      3.003;GOOG;GoogleSans-Italic
+      3.001;GOOG;GoogleSans-Italic
     </namerecord>
     <namerecord nameID="4" platformID="3" platEncID="1" langID="0x409">
-      Google Sans Italic
+      GoogleSansItalic Italic
     </namerecord>
     <namerecord nameID="5" platformID="3" platEncID="1" langID="0x409">
-      Version 3.003
+      Version 3.001
     </namerecord>
     <namerecord nameID="6" platformID="3" platEncID="1" langID="0x409">
       GoogleSans-Italic
@@ -93,7 +60,7 @@
       Google LLC
     </namerecord>
     <namerecord nameID="9" platformID="3" platEncID="1" langID="0x409">
-      Google Sans Authors
+      Jesse Kaczmarek, Colophon Foundry
     </namerecord>
     <namerecord nameID="11" platformID="3" platEncID="1" langID="0x409">
       https://design.google
@@ -123,46 +90,13 @@
       Bulgarian Locale
     </namerecord>
     <namerecord nameID="263" platformID="3" platEncID="1" langID="0x409">
-      Optical size
+      Optical Size
     </namerecord>
     <namerecord nameID="264" platformID="3" platEncID="1" langID="0x409">
       Weight
     </namerecord>
     <namerecord nameID="265" platformID="3" platEncID="1" langID="0x409">
-      Italic
-    </namerecord>
-    <namerecord nameID="266" platformID="3" platEncID="1" langID="0x409">
-      Medium Italic
-    </namerecord>
-    <namerecord nameID="267" platformID="3" platEncID="1" langID="0x409">
-      Bold Italic
-    </namerecord>
-    <namerecord nameID="268" platformID="3" platEncID="1" langID="0x409">
-      Text Italic
-    </namerecord>
-    <namerecord nameID="269" platformID="3" platEncID="1" langID="0x409">
-      Text Medium Italic
-    </namerecord>
-    <namerecord nameID="270" platformID="3" platEncID="1" langID="0x409">
-      Text Bold Italic
-    </namerecord>
-    <namerecord nameID="271" platformID="3" platEncID="1" langID="0x409">
-      Optical Size
-    </namerecord>
-    <namerecord nameID="272" platformID="3" platEncID="1" langID="0x409">
-      Max
-    </namerecord>
-    <namerecord nameID="273" platformID="3" platEncID="1" langID="0x409">
-      Text
-    </namerecord>
-    <namerecord nameID="274" platformID="3" platEncID="1" langID="0x409">
-      Regular
-    </namerecord>
-    <namerecord nameID="275" platformID="3" platEncID="1" langID="0x409">
-      Medium
-    </namerecord>
-    <namerecord nameID="276" platformID="3" platEncID="1" langID="0x409">
-      Bold
+      GRAD
     </namerecord>
   </name>
```

</details>

**Comment by chrissimpkins** [comment]
Named instances addressed downstream in https://github.com/googlefonts/GoogleSans-fb/commit/51576a2c91e5ecd91ff389e3ebe59bf8d0e59ffd

Family name regressions addressed downstream in https://github.com/googlefonts/GoogleSans-fb/commit/005c6f74d3bf744d6a7b16b86ada75c5b368b2bb

**Comment by chrissimpkins** [comment]
GS v4 build static instance name tables LGTM as of #240
