### ISSUE TITLE
[GS v4] OS/2 diff

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#226]
Review diff of OS/2 tables between David Berlow's builds @ googlefonts/GoogleSans-fb@a8d2737 and our v3.003 production releases

### TODO

- [x] set fsSelection bit 7 Roman and Italic builds (https://github.com/googlefonts/googlesans/issues/225)
- [x] set Hebrew Unicode range in Italic sources
- [x] revert strikeout size change back to 84 from 50

**Comment by chrissimpkins** [comment]
Roman var font

- strikeout size changes from 84 to 50 (https://github.com/googlefonts/GoogleSans-fb/issues/16)
- fsSelection bit 7 changed to unset (#225)

<details>
<summary> diff</summary>

```diff
--- A/GoogleSans[opsz,wght].ttf	2020-09-16T16:50:43-04:00
+++ B/GoogleSansGrades-VF.ttf	2021-02-25T11:12:08.527802-05:00
@@ -5,7 +5,7 @@
     <!-- The fields 'usFirstCharIndex' and 'usLastCharIndex'
          will be recalculated by the compiler -->
     <version value="4"/>
-    <xAvgCharWidth value="590"/>
+    <xAvgCharWidth value="577"/>
     <usWeightClass value="400"/>
     <usWidthClass value="5"/>
     <fsType value="00000000 00000000"/>
@@ -17,7 +17,7 @@
     <ySuperscriptYSize value="600"/>
     <ySuperscriptXOffset value="0"/>
     <ySuperscriptYOffset value="350"/>
-    <yStrikeoutSize value="84"/>
+    <yStrikeoutSize value="50"/>
     <yStrikeoutPosition value="306"/>
     <sFamilyClass value="0"/>
     <panose>
@@ -37,7 +37,7 @@
     <ulUnicodeRange3 value="00000000 00000000 00000000 00000000"/>
     <ulUnicodeRange4 value="00000000 00000000 00000000 00000000"/>
     <achVendID value="GOOG"/>
-    <fsSelection value="00000000 11000000"/>
+    <fsSelection value="00000000 01000000"/>
     <usFirstCharIndex value="2"/>
     <usLastCharIndex value="65533"/>
     <sTypoAscender value="966"/>
```

</details>

**Comment by chrissimpkins** [comment]
Italic var font

- strikeout size changes from 84 to 50 (https://github.com/googlefonts/GoogleSans-fb/issues/16)
- fsSelection bit 7 changed to unset (#225)
- need to set Hebrew Unicode range

<details>
<summary> diff</summary>

```diff
--- A/GoogleSans-Italic[opsz,wght].ttf	2020-09-16T16:50:43-04:00
+++ B/GoogleSansItalicGrades-VF.ttf	2021-02-25T11:12:48.431719-05:00
@@ -5,7 +5,7 @@
     <!-- The fields 'usFirstCharIndex' and 'usLastCharIndex'
          will be recalculated by the compiler -->
     <version value="4"/>
-    <xAvgCharWidth value="590"/>
+    <xAvgCharWidth value="582"/>
     <usWeightClass value="400"/>
     <usWidthClass value="5"/>
     <fsType value="00000000 00000000"/>
@@ -17,7 +17,7 @@
     <ySuperscriptYSize value="600"/>
     <ySuperscriptXOffset value="62"/>
     <ySuperscriptYOffset value="350"/>
-    <yStrikeoutSize value="84"/>
+    <yStrikeoutSize value="50"/>
     <yStrikeoutPosition value="306"/>
     <sFamilyClass value="0"/>
     <panose>
@@ -32,12 +32,12 @@
       <bMidline value="0"/>
       <bXHeight value="0"/>
     </panose>
-    <ulUnicodeRange1 value="00000000 00000000 00001010 10000111"/>
+    <ulUnicodeRange1 value="00000000 00000000 00000010 10000111"/>
     <ulUnicodeRange2 value="00000000 00000000 00000000 00000000"/>
     <ulUnicodeRange3 value="00000000 00000000 00000000 00000000"/>
     <ulUnicodeRange4 value="00000000 00000000 00000000 00000000"/>
     <achVendID value="GOOG"/>
-    <fsSelection value="00000000 10000001"/>
+    <fsSelection value="00000000 00000001"/>
     <usFirstCharIndex value="2"/>
     <usLastCharIndex value="65533"/>
     <sTypoAscender value="966"/>
```

</details>

**Comment by chrissimpkins** [comment]
fixed downstream

**Comment by chrissimpkins** [comment]
Strikeout size fix and Unicode bit 11 definition confirmed as of https://github.com/googlefonts/googlesans/pull/240/commits/b26739deb19ca6740903a69df7499c8851ff868a

Added fontbakery check for OS/2 strikeout size and position in https://github.com/googlefonts/googlesans/pull/240/commits/ee5bf72fc4340b405d2cbde904f65c5972729cdd

This will be merged in #240.  #240 closes this issue.
