### ISSUE TITLE
Review and update vertical metrics following Lao import

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#423]
We are seeing clipping in Windows application environments with the new Lao (#416) and Khmer (#417) designs.  We will need to adjust our Win v metrics settings to address this.  We use typo metrics for line spacing so this should not impact line:line leading.  We don't want to adjust this default and may see line:line collisions.  My understanding based on discussion with the Cadson Demak team is that the deep / tall forms involved are rarely used.

@madig Will you please list the affected glyphs that your design team identified in this thread?  Ty!

### TODO:

- [x] review affected glyphs
- [x] modify Win metrics to exceed yMin and yMax values
- [x] review fonts with updated metrics in Win env
- [x] update fontbakery checks
- [ ] discuss https://github.com/googlefonts/googlesans/pull/416#issuecomment-999748412 with Si Daniels (Microsoft) - moved to #435

**Comment by madig** [comment]
For Lao, it seemed to be most glyphs that stack two or more marks on top. For Khmer, it was glyphs that stack two or more marks below. So, I assume this affects all glyphs that stack marks.

**Comment by chrissimpkins** [comment]
> For Lao, it seemed to be most glyphs that stack two or more marks on top. For Khmer, it was glyphs that stack two or more marks below. So, I assume this affects all glyphs that stack marks.

@cadsondemakoffice the very tall/deep base form + mark form combinations are uncommonly used correct? We will look into the clipping issue.
