### ISSUE TITLE
Add Myanmar script support

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#470]
Sources available on repository: **[TBD]**

### TODO

- [ ] @ohbendy & @simoncozens confirmation that this date fits their schedule
- [x] review [Myanmar-specific binary merge approach](https://github.com/googlefonts/googlesans/issues/470#issuecomment-1071006903) and determine how that fits into the "Google Sans" family build workflow, including an assessment of longer term maintenance issues as upstream ("Google Sans") and downstream ("Google Sans Myanmar") change.
- [ ] can we merge at the UFO source level?  d/w Simon and it may be possible to create "traditional" per master fea file organization that is required to do this.  

cc @madig @belluzj

**Comment by simoncozens** [comment]
As far as I'm concerned, end of this month (two weeks!) is doable. There are only a few outstanding issues for this release and I'm eager to get it done by EOQ1. I haven't responded to the timeline because I think the decisive factor will be Ben's QA evaluation, and I'm not sure where that's up to.

We already use fontbakery shaping tests, so supplying test strings is not a problem. You should be aware that we use a variable-first build process - the VF is created first and then layout rules are added from a variable layout file. I would not expect a source-based merge to work and recommend a binary merge. Fortunately I've just managed to come up with a script to merge GS into GS Myanmar, so you should be able to adapt it to merge GS Myanmar into GS!

**Comment by chrissimpkins** [comment]
> We already use fontbakery shaping tests, so supplying test strings is not a problem. You should be aware that we use a variable-first build process - the VF is created first and then layout rules are added from a variable layout file. I would not expect a source-based merge to work and recommend a binary merge. Fortunately I've just managed to come up with a script to merge GS into GS Myanmar, so you should be able to adapt it to merge GS Myanmar into GS!

Mind sharing the merge implementation with us asap so that we can determine if this will be possible and fits into our source merge timeline assumptions?

We'll wait to hear back from Ben re: the QA before we commit to any dates.

**Comment by simoncozens** [comment]
Sure, here's the merge script. I found a couple of fontToos.varLib.merger bugs in the process, so you will need the latest from git...

```python
from fontTools.ttLib import TTFont
from fontTools.merge import Merger
from fontTools.varLib import instancer, build
from fontTools.subset import Subsetter, Options
from tempfile import TemporaryDirectory
from fontTools.designspaceLib import DesignSpaceDocument
from pathlib import Path
import glob
import re
from copy import deepcopy
from glyphsets.codepoints import CodepointsInSubset
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("--ui", action="store_true", help="build UI versions")

args = parser.parse_args()

myanmar = TTFont("variable_ttf/GoogleSansMyanmar-Everything.ttf")
latin_core = CodepointsInSubset("GF Glyph Sets/GF-latin-core")

if args.ui:
    uipart = "-UI"
else:
    uipart = ""

upright_mapping = [
    ({"wght": 400, "opsz": 17}, "GoogleSans-opsz17-wght380-GRAD0.ttf"),
    ({"wght": 700, "opsz": 17}, "GoogleSans-opsz17-wght734-GRAD0.ttf"),
    ({"wght": 400, "opsz": 18}, "GoogleSans-opsz18-wght380-GRAD0.ttf"),
    ({"wght": 700, "opsz": 18}, "GoogleSans-opsz18-wght734-GRAD0.ttf"),
]

italic_mapping = [
    ({"wght": 400, "opsz": 17}, "GoogleSansItalic-opsz17-wght380-GRAD0.ttf"),
    ({"wght": 700, "opsz": 17}, "GoogleSansItalic-opsz17-wght734-GRAD0.ttf"),
    ({"wght": 400, "opsz": 18}, "GoogleSansItalic-opsz18-wght380-GRAD0.ttf"),
    ({"wght": 700, "opsz": 18}, "GoogleSansItalic-opsz18-wght734-GRAD0.ttf"),
]


def merge_an_instance(latin_file, coords):
    print("Merging %s with %s" % (latin_file, coords))
    with TemporaryDirectory() as tmpdir:
        tmpdir = Path(tmpdir)

        latin = TTFont("upstream-interpolatable/%s" % latin_file)
        print(" Subsetting %s to just Latin Core" % latin_file)
        add_latin = Subsetter(
            options=Options(layout_scripts=["latn"], notdef_outline=True)
        )
        add_latin.populate(unicodes=latin_core)
        add_latin.subset(latin)
        latin.save(tmpdir / "latin.ttf")

        print(" Partially instantiating %s" % coords)
        partial_myanmar = instancer.instantiateVariableFont(
            myanmar, coords, optimize=False
        )
        # Original plan was to drop any Latin from the Myanmar source,
        # but that isn't optimal because you lose kerning. So we won't
        # do that.
        #
        # myanmar_glyphs = set(partial_myanmar.getGlyphOrder()) - set(
        #     latin.getGlyphOrder()
        # )
        # drop_latin = Subsetter(options=Options(notdef_glyph=False))
        # drop_latin.populate(glyphs=myanmar_glyphs)
        # drop_latin.subset(partial_myanmar)
        partial_myanmar.save(tmpdir / "myanmar.ttf")

        merged = Merger().merge(
            fontfiles=[tmpdir / "myanmar.ttf", tmpdir / "latin.ttf"]
        )
        return merged


def loc2loc(ds, source):
    name2ax = {ax.name: ax for ax in ds.axes}
    return frozenset(
        {
            name2ax[k].tag: int(name2ax[k].map_backward(v))
            for k, v in source.location.items()
        }.items()
    )


## Upright
instances = {}
for ix, (loc, latin) in enumerate(upright_mapping):
    full_loc = dict(loc)
    full_loc["GSUI"] = int(args.ui)
    full_loc["ital"] = 0
    instance = merge_an_instance(latin, full_loc)
    instance.save("Instance-%i.ttf" % ix)
    instances[frozenset(loc.items())] = "Instance-%i.ttf" % ix

upright_ds = DesignSpaceDocument.fromfile("master_ufo/GoogleSansMyanmar.designspace")
# Drop all italic-related stuff
upright_ds.axes = [x for x in upright_ds.axes if x.tag != "ital" and x.tag != "GSUI"]
upright_ds.sources = [
    x
    for x in upright_ds.sources
    if x.location["Italic"] == 0.0 and x.location["UI Build"] == int(args.ui)
]
for ix, source in enumerate(upright_ds.sources):
    del source.location["Italic"]
    del source.location["UI Build"]
    source.path = instances[loc2loc(upright_ds, source)]

upright_ds.instances = [
    x
    for x in upright_ds.instances
    if x.location["Italic"] == 0.0 and x.location["UI Build"] == int(args.ui)
]
for instance in upright_ds.instances:
    del instance.location["Italic"]
    del instance.location["UI Build"]

variable = build(upright_ds)
variable[0].save("fonts/ttf/GoogleSansMyanmar%s-VF.ttf" % uipart)

## Italic
instances = {}
for ix, (loc, latin) in enumerate(italic_mapping):
    full_loc = dict(loc)
    full_loc["GSUI"] = int(args.ui)
    full_loc["ital"] = 1
    instance = merge_an_instance(latin, full_loc)
    instance.save("Italic-%i.ttf" % ix)
    instances[frozenset(loc.items())] = "Italic-%i.ttf" % ix

italic_ds = DesignSpaceDocument.fromfile("master_ufo/GoogleSansMyanmar.designspace")
# Drop all italic-related stuff
italic_ds.axes = [x for x in italic_ds.axes if x.tag != "ital" and x.tag != "GSUI"]
italic_ds.sources = [
    x
    for x in italic_ds.sources
    if x.location["Italic"] == 1.0 and x.location["UI Build"] == int(args.ui)
]
for ix, source in enumerate(italic_ds.sources):
    del source.location["Italic"]
    del source.location["UI Build"]
    source.path = instances[loc2loc(italic_ds, source)]

italic_ds.instances = [
    x
    for x in italic_ds.instances
    if x.location["Italic"] == 1.0 and x.location["UI Build"] == int(args.ui)
]
for instance in italic_ds.instances:
    del instance.location["Italic"]
    del instance.location["UI Build"]

variable = build(italic_ds)
variable[0].save("fonts/ttf/GoogleSansMyanmar-Italic%s-VF.ttf" % uipart)
```

**Comment by ohbendy** [comment]
> Ben's QA evaluation, and I'm not sure where that's up to.

Hard to know as I haven't looked at the font exports from your build recently. I'll wrap up everything in the source file by the start of next week,  but it'll definitely take me a while to go through the tests, checking the behaviour of everything. Then it will depend on what I find whether there might be things for Simon to adjust.

**Comment by madig** [comment]
@simoncozens just so I understand, GS Myanmar is a compatible Upright + Italic VF and your script takes the already-compiled normal GS builds, strips them down to basic Latin and stuffs that into the separate upright and italic Myanmar instances? What are the UI builds, how do they integrate with the existing GS setup? What are the reasons a source-merge may not work?

**Comment by simoncozens** [comment]
> GS Myanmar is a compatible Upright + Italic VF 

Yes, and it also has a (autogenerated) GSUI axis.

> your script takes the already-compiled normal GS builds, strips them down to basic Latin and stuffs that into the separate upright and italic Myanmar instances

Yes, but then it re-builds those instances back into upright and italic VFs for delivery to you.

> What are the UI builds, how do they integrate with the existing GS setup? 

Our build process is:

1. Generate variable feature file from FEZ + Glyphs sources.
2. Use fontmake to convert Glyphs (single file with both italic/upright) to UFO.
3. Create transformed UFOs for UI axis and add them to the designspace.
4. Use fontmake to turn new designspace to VF.
5. Use fontTools.feaLib to add features to VF.
6. Merge upstream GS Latin.

> What are the reasons a source-merge may not work?

You're using "classical" *per-master* feature files which get added to each master, before the masters are merged together into a VF. We're building the VF first and then using a *variable* feature file which gets added to it. (We do this because we need contextual positioning rules which vary across the axes.) I can't see where our feature file would get added into your process - if you add our features to your font after the VF build, you wipe out all the existing (non-Myanmar) features.

**Comment by madig** [comment]
Ok thanks. More questions:

* What does the GSUI axis do? Upstream GS has no such axis. How would we integrate it?
* How is the variable feature file compiled for the VFs and statics?

**Comment by simoncozens** [comment]
GSUI is the UI axis mentioned above. It’s  added by a script which takes the original designspace, transforms the Burmese glyphs in each UFO, saves them as “UI” UFOs and adds them back into the designspace.

Variable feature file is compiled into the VF with fonttools feaLib as mentioned above. Everything else - regular, italic, UI, non-UI, language-specific builds - are instantiated from the single VF.

I suppose I could come up with a way of instantiating the variable layout file, and then I could give you a glyphs file and a set of feature files. That might be easier all round…

**Comment by chrissimpkins** [comment]
@madig No plan to integrate a UI axis upstream.  That is a downstream family only feature for Android environments.

**Comment by chrissimpkins** [comment]
> > Ben's QA evaluation, and I'm not sure where that's up to.
> 
> 
> 
> Hard to know as I haven't looked at the font exports from your build recently. I'll wrap up everything in the source file by the start of next week,  but it'll definitely take me a while to go through the tests, checking the behaviour of everything. Then it will depend on what I find whether there might be things for Simon to adjust.

@belluzj @madig Based on this info it sounds like we will need to push this back into mid to late April.  Let's give back your April design team time.  I will chat with Ben once he has an opportunity to go through the current state of things and understand how long his review will take.  

Thanks all!

**Comment by ohbendy** [comment]
I believe my design work is finished now. I'll spend the next couple of weeks checking Simon's build in all the testing documents. Hopefully there won't be too much to fix but yes, better to be on the safe side in case we hit any snags. :-)

**Comment by belluzj** [comment]
@chrissimpkins noted, I'll push back the design team's time.

**Comment by chrissimpkins** [comment]
Requested access to the GS Myanmar repo for Jany and Nikolaus.  We are going to review the sources and build process to decide if/how we should approach an upstream merge.  In the meantime, Ben will continue with his QA work and I'll chat with him about timing of the production ready designs during the upcoming week.

**Comment by chrissimpkins** [comment]
@madig @belluzj you should now have access to the GS Myanmar repository.

**Comment by madig** [comment]
Thanks, yes. I haven't yet fully understood the build process but will try to leanr more for next monday.

**Comment by chrissimpkins** [comment]
> I believe my design work is finished now. I'll spend the next couple of weeks checking Simon's build in all the testing documents. Hopefully there won't be too much to fix but yes, better to be on the safe side in case we hit any snags. :-)

I spoke with Ben today. Tentatively looking at April 8 source delivery, but let's give this a bit more time for Ben to speak with his design review consultants and us to understand how to approach a merge before we commit to a new DaMa design review date.

**Comment by chrissimpkins** [comment]
@ohbendy Ben, do you have more current info on timing of the Myanmar designs following your conversation with consultant teams.  How are we looking?

**Comment by chrissimpkins** [comment]
@simoncozens I spoke with Ben today and he is interested to know where you are with technical fixes that are in progress.  He wants to wait until these are in place to distribute the files to  his consultant teams.

**Comment by chrissimpkins** [comment]
D/W Simon.  He is going to work through the final set of font engineering issues this week and Ben will distribute the files to his sub-contracted Myanmar type design consultants next week.

**Comment by chrissimpkins** [comment]
@simoncozens The [latest GS Myanmar Roman and Italic builds](https://github.com/simoncozens/Google-Sans-Myanmar/actions/runs/2070313300) are running approx 1.4MB per VF file.  This includes (only) Latin Core + Myanmar correct?

**Comment by chrissimpkins** [comment]
We will release Myanmar as a separate "Google Sans Myanmar" typeface family.

**Comment by simoncozens** [comment]
Good to know. Chris, please confirm the deliverables you want from us in that case.
