### ISSUE TITLE
Merge Armenian script sources

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#57]
Merge the Armenian script work by @gorjious 

## Prep

- [ ] move opsz 14 master to 17
- [ ] address brace and bracket layers with opsz master move
- [ ] develop script prefix for new classes (e.g., `armn_[class name]`)

## TODO

Merge work list TKTKTK

**Comment by chrissimpkins** [comment]
@gorjious Gor, will you please have a look at the [prep list](https://github.com/googlefonts/googlesans/issues/57#issue-637838592) and begin to think through the approach to these issues while you wrap up the production work and we get ready to merge your designs next quarter?

We will need to make the optical size axis transition and figure out how to address brace/bracket layers that are currently defined in an optical size axis that supports interpolation.  @Colophon-Foundry is going to work on this in the Latin/Greek/Cyrillic sets next week.  Please keep an eye on the repo threads for information about the approach and don't hesitate to ask questions or point out concerns/issues in your script area.  Let's make sure that the approach will work for you.

**Comment by chrissimpkins** [comment]
Tracker for the opsz axis transition: https://github.com/googlefonts/googlesans/issues/49

**Comment by chrissimpkins** [comment]
opening a new issue for this following our UFO source transition and new merge approach
