### ISSUE TITLE
Merge Georgian script sources

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#58]
Merge the Georgian script work by @razmadzekoko 

## Prep

- [ ] move opsz 14 master to 17
- [ ] address brace and bracket layers with opsz master move
- [ ] develop script prefix for new classes (e.g., `geor_[class name]`)
- [ ] review Georgian feature code vs. current upstream Google Sans feature code for conflicts

## TODO

Merge work list TKTKTK

**Comment by chrissimpkins** [comment]
@razmadzekoko Akaki, will you please have a look at the [prep list](https://github.com/googlefonts/googlesans/issues/58#issue-637842238) and begin to think through the approach to these issues while you wrap up the production work and we get ready to merge your designs next quarter?

We will need to make the optical size axis transition and figure out how to address brace/bracket layers that are currently defined in an optical size axis that supports interpolation.  @Colophon-Foundry is going to work on this in the Latin/Greek/Cyrillic sets next week.  Please keep an eye on the repo threads for information about the approach and don't hesitate to ask questions or point out concerns/issues in your script area.  Let's make sure that the approach will work for you.

**Comment by chrissimpkins** [comment]
Tracker for the opsz axis transition https://github.com/googlefonts/googlesans/issues/49

**Comment by chrissimpkins** [comment]
issue tracker superseded by #87

**Comment by razmadzekoko** [comment]
Thank you @chrissimpkins 
I just uploaded the new files to my [repository](https://github.com/razmadzekoko/google-sans/tree/master/source/Marged_with_current_Latin_26.06.2020)
New files contain Georgian  currency symbol variations.

There is only one character in Georgian set with bracket layers:
<img width="526" alt="Screen Shot 2020-09-14 at 14 19 07" src="https://user-images.githubusercontent.com/18236719/93074933-1ec55e80-f696-11ea-9142-90c28c5fb73e.png">
it should have the same opsz definitions.

**Comment by chrissimpkins** [comment]
> Thank you @chrissimpkins
> I just uploaded the new files to my [repository](https://github.com/razmadzekoko/google-sans/tree/master/source/Marged_with_current_Latin_26.06.2020)
> New files contain Georgian currency symbol variations.
> 
> There is only one character in Georgian set with bracket layers:
> <img alt="Screen Shot 2020-09-14 at 14 19 07" width="526" src="https://user-images.githubusercontent.com/18236719/93074933-1ec55e80-f696-11ea-9142-90c28c5fb73e.png">
> it should have the same opsz definitions.

Thank you Akaki!
