### ISSUE TITLE
Georgian script merge (old)

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#87]
**Note**: superseded by https://github.com/googlefonts/googlesans/issues/309

---

Target release v3.004

Tracker for the Georgian merge work

### Downstream Sources for Merge

https://github.com/razmadzekoko/google-sans/tree/master/source/Marged_with_current_Latin_26.06.2020

Downstream files added to Georgian branch in https://github.com/googlefonts/googlesans/commit/955fd4272dfecd70fcf6f29262ce1a0e09fd24f5

Downstream files modified to normalize *.glyphs text in preparation for the merge in https://github.com/googlefonts/googlesans/commit/0315e54a3e15dbe2174f48f34b76bbaf0643b9ab

### TODO

- [x] normalize downstream source files with new glyphsLib script (script added in #89, this change made in https://github.com/googlefonts/googlesans/commit/0315e54a3e15dbe2174f48f34b76bbaf0643b9ab)
- [x] merge all *-georgian outlines
- [x] merge all *-loclGEO outlines (includes localized punctuation)
- [x] confirm semicolon-loclGEO bracket layers @ [18] (see https://github.com/googlefonts/googlesans/issues/58#issuecomment-691965326)
- [x] merge paragraph-georgian.case
- [x] merge lari currency symbol outline
- [x] merge lari tabular and case form outlines (#88)
- [x] merge kerning
- [x] merge geor_uppercase and geor_lowercase glyph classes
- [x] add spaces.all glyph class (converted name to spaces_all)
- [x] add punctuation.all glyph class (converted name to punctuation_all)
- [x] add punctuation.centered glyph class (converted name to punctuation_centered)
- [x] merge fea code updates
    - [x] case
    - [x] locl
    - [x] calt
    - [x] lari currency symbol case and tnum updates (#88)
- [x] rename spaces.all, punctuation.all, punctuation.centered to spaces_all, punctuation_all, punctuation_centered in fea code (names changed to maintain consistency with other feature classes)
- [x] update Unicode range with Georgian script
- [x] update language systems registrations with Georgian script
- [ ] fix `calt` feature code for Georgian alpha-Latin punctuation-Georgian position of colon + semicolon (see https://github.com/googlefonts/googlesans/pull/93#issuecomment-702830282)

### Questions for Akaki

- [x] tabular form of lari currency symbol? (decision: to be designed and will be merged into v3.004 updates)
- [x] case form of lari currency symbol? (decision: to be designed and will be merged into v3.004 updates)
 
--- 

cc @razmadzekoko

**Comment by chrissimpkins** [comment]
We will add the tabular and case forms of the lari currency symbol in the v3.004 work. Akaki is working on these designs now.

#88

**Comment by chrissimpkins** [comment]
Georgian currency symbol updates are now available in these sources https://github.com/razmadzekoko/google-sans/tree/master/source/Marged_with_current_Latin_26.06.2020

**Comment by chrissimpkins** [comment]
Akaki's downstream sources were added to the Georgian branch in 955fd4272dfecd70fcf6f29262ce1a0e09fd24f5

**Comment by chrissimpkins** [comment]
downstream glyphs source files normalized to avoid text formatting-associated source file diffs in 0315e54a3e15dbe2174f48f34b76bbaf0643b9ab

**Comment by chrissimpkins** [comment]
PR #93 includes the merge work

**Comment by chrissimpkins** [comment]
@razmadzekoko @gorjious I am merging your new feature classes with slightly modified names.  We are using underscores as word separators rather than periods.  So the class names will be: `spaces_all`, `punctuation_all`, `punctuation_centered`.  Please let me know if you have any concerns about this approach.

**Comment by gorjious** [comment]
No concern. I will update the rest of my feature classes to follow this format.

**Comment by chrissimpkins** [comment]
> No concern. I will update the rest of my feature classes to follow this format.

thanks Gor!

**Comment by chrissimpkins** [comment]
Merge complete.  Source and builds are in review
